spring:
  application:
    name: TaskManagment

  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: task_manager_app
    password: Forgot@247

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE